org: open-cvbaba
app: open-cvbaba
service: fastapi-lambda

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  environment:
    PYTHONPATH: "./"

functions:
  app:
    handler: app.main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: any

package:
  individually: false
  patterns:
    - '!node_modules/**'
    - '!.serverless/**'
    - '!.git/**'
    - '!env/**'
    - '!tests/**'
    - '!.DS_Store'
    - '!myenv/**'
    - '!**/.vscode/**'
    - '!**/__pycache__/**'
    - '!**/*.pyc'
    - '.env'