import Link from 'next/link';

const milestones = [
  ['2024', 'Research begins', 'AI could generate text and code, but reliably producing a real, polished, compilable document end to end was still difficult.'],
  ['2024', 'LaTeX tooling and data research', 'The first experiments focused on browser-friendly LaTeX compilation and structured annotation for high-quality LaTeX CV data.'],
  ['2025', 'Editable HTML documents', 'HTML became the practical format for a faster WYSIWYG workflow. That direction became CVBaba and grew through real usage and community interest.'],
  ['Now', 'Open-source document creation', 'open-cvbaba is the self-hostable continuation: a local-first workspace for creating CVs, letters, books, and ebooks with Mistral-powered generation.'],
];

export default function AboutPage() {
  return <main className="min-h-screen bg-slate-50 px-6 py-12 text-slate-950 sm:py-20"><div className="mx-auto max-w-4xl">
    <Link href="/" className="text-sm font-semibold text-blue-600 hover:text-blue-800">← Back to open-cvbaba</Link>
    <header className="mt-10 max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">About the project</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">From document research to an open-source AI workspace.</h1><p className="mt-6 text-lg leading-8 text-slate-600">open-cvbaba is an experiment in making AI-assisted document creation reliable, editable, and easy to run locally.</p></header>
    <section className="mt-16 rounded-3xl border border-slate-200 bg-white p-8 shadow-sm sm:p-10"><h2 className="text-2xl font-bold">Why it started</h2><div className="mt-5 space-y-5 leading-8 text-slate-600"><p>In 2024, I noticed that AI tools could generate useful text and code, but they still struggled to produce a real document end to end. The workflow was frustrating: copy code from an LLM, paste it into another tool, compile it, discover quality problems, and repeat.</p><p>That led to a research direction focused on the complete path from a prompt to a usable PDF: generation, layout, compilation, preview, editing, and export. The goal was not only to generate content, but to make the result something a person could actually use.</p></div></section>
    <section className="mt-16"><h2 className="text-2xl font-bold">Research path</h2><div className="mt-8 space-y-5">{milestones.map(([year,title,text]) => <article key={year} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-6 sm:grid-cols-[100px_1fr] sm:gap-6"><p className="font-semibold text-blue-600">{year}</p><div><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 leading-7 text-slate-600">{text}</p></div></article>)}</div></section>
    <section className="mt-16 grid gap-6 md:grid-cols-2"><div className="rounded-3xl bg-slate-900 p-8 text-white"><h2 className="text-2xl font-bold">What we are building</h2><p className="mt-4 leading-7 text-slate-300">A focused, open-source environment where document history stays in PostgreSQL, generation uses Mistral, and output remains editable HTML that can be rendered to PDF.</p></div><div className="rounded-3xl border border-slate-200 bg-white p-8"><h2 className="text-2xl font-bold">What comes next</h2><p className="mt-4 leading-7 text-slate-600">The project is open to research, experiments, templates, evaluation, and improvements to the agentic prompt-to-document workflow.</p></div></section>
    <section className="mt-16 rounded-3xl border border-blue-100 bg-blue-50 p-8"><h2 className="text-2xl font-bold">Earlier research projects</h2><ul className="mt-5 space-y-3 leading-7 text-slate-700"><li><a className="font-semibold text-blue-700 hover:underline" href="https://github.com/ialim0/latex-compiler-api">latex-compiler-api</a> — browser-friendly LaTeX compilation experiments.</li><li><a className="font-semibold text-blue-700 hover:underline" href="https://github.com/ialim0/db-cvbaba">db-cvbaba</a> — structured annotation and dataset tooling for CV generation research.</li></ul></section>
    <footer className="mt-12 flex flex-wrap gap-5 text-sm font-semibold text-slate-600"><Link href="/" className="hover:text-blue-600">Create a document</Link><a href="https://github.com/ialim0" className="hover:text-blue-600">GitHub</a><Link href="/privacy" className="hover:text-blue-600">Privacy</Link></footer>
  </div></main>;
}
